version: '2'
services:
  app2:
    build: ../../
    environment:
      DSN: postgres://postgres:adminadmin@postgres:5432/codeforces
      KAFKA_CONN: kafka:9092
      PEER: peer1
      PORT: :8081
    ports: 
      - 8081:8081