// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserRepositoryClient is the client API for UserRepository service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserRepositoryClient interface {
	All(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UserList, error)
	ById(ctx context.Context, in *UserRequestId, opts ...grpc.CallOption) (*User, error)
	Create(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	Update(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	Delete(ctx context.Context, in *UserRequestId, opts ...grpc.CallOption) (*Empty, error)
}

type userRepositoryClient struct {
	cc grpc.ClientConnInterface
}

func NewUserRepositoryClient(cc grpc.ClientConnInterface) UserRepositoryClient {
	return &userRepositoryClient{cc}
}

func (c *userRepositoryClient) All(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UserList, error) {
	out := new(UserList)
	err := c.cc.Invoke(ctx, "/api.UserRepository/All", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRepositoryClient) ById(ctx context.Context, in *UserRequestId, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/api.UserRepository/ById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRepositoryClient) Create(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/api.UserRepository/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRepositoryClient) Update(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/api.UserRepository/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRepositoryClient) Delete(ctx context.Context, in *UserRequestId, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.UserRepository/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserRepositoryServer is the server API for UserRepository service.
// All implementations must embed UnimplementedUserRepositoryServer
// for forward compatibility
type UserRepositoryServer interface {
	All(context.Context, *Empty) (*UserList, error)
	ById(context.Context, *UserRequestId) (*User, error)
	Create(context.Context, *User) (*User, error)
	Update(context.Context, *User) (*User, error)
	Delete(context.Context, *UserRequestId) (*Empty, error)
	mustEmbedUnimplementedUserRepositoryServer()
}

// UnimplementedUserRepositoryServer must be embedded to have forward compatible implementations.
type UnimplementedUserRepositoryServer struct {
}

func (UnimplementedUserRepositoryServer) All(context.Context, *Empty) (*UserList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method All not implemented")
}
func (UnimplementedUserRepositoryServer) ById(context.Context, *UserRequestId) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ById not implemented")
}
func (UnimplementedUserRepositoryServer) Create(context.Context, *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedUserRepositoryServer) Update(context.Context, *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedUserRepositoryServer) Delete(context.Context, *UserRequestId) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedUserRepositoryServer) mustEmbedUnimplementedUserRepositoryServer() {}

// UnsafeUserRepositoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserRepositoryServer will
// result in compilation errors.
type UnsafeUserRepositoryServer interface {
	mustEmbedUnimplementedUserRepositoryServer()
}

func RegisterUserRepositoryServer(s grpc.ServiceRegistrar, srv UserRepositoryServer) {
	s.RegisterService(&UserRepository_ServiceDesc, srv)
}

func _UserRepository_All_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRepositoryServer).All(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserRepository/All",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRepositoryServer).All(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRepository_ById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequestId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRepositoryServer).ById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserRepository/ById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRepositoryServer).ById(ctx, req.(*UserRequestId))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRepository_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRepositoryServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserRepository/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRepositoryServer).Create(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRepository_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRepositoryServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserRepository/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRepositoryServer).Update(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRepository_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequestId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRepositoryServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserRepository/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRepositoryServer).Delete(ctx, req.(*UserRequestId))
	}
	return interceptor(ctx, in, info, handler)
}

// UserRepository_ServiceDesc is the grpc.ServiceDesc for UserRepository service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserRepository_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.UserRepository",
	HandlerType: (*UserRepositoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "All",
			Handler:    _UserRepository_All_Handler,
		},
		{
			MethodName: "ById",
			Handler:    _UserRepository_ById_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _UserRepository_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _UserRepository_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _UserRepository_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/api/service.proto",
}

// SubmissionRepositoryClient is the client API for SubmissionRepository service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubmissionRepositoryClient interface {
	All(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SubmissionList, error)
	ById(ctx context.Context, in *SubmissionRequestId, opts ...grpc.CallOption) (*Submission, error)
	Create(ctx context.Context, in *Submission, opts ...grpc.CallOption) (*Submission, error)
	Update(ctx context.Context, in *Submission, opts ...grpc.CallOption) (*Submission, error)
	Delete(ctx context.Context, in *SubmissionRequestId, opts ...grpc.CallOption) (*Empty, error)
}

type submissionRepositoryClient struct {
	cc grpc.ClientConnInterface
}

func NewSubmissionRepositoryClient(cc grpc.ClientConnInterface) SubmissionRepositoryClient {
	return &submissionRepositoryClient{cc}
}

func (c *submissionRepositoryClient) All(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SubmissionList, error) {
	out := new(SubmissionList)
	err := c.cc.Invoke(ctx, "/api.SubmissionRepository/All", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *submissionRepositoryClient) ById(ctx context.Context, in *SubmissionRequestId, opts ...grpc.CallOption) (*Submission, error) {
	out := new(Submission)
	err := c.cc.Invoke(ctx, "/api.SubmissionRepository/ById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *submissionRepositoryClient) Create(ctx context.Context, in *Submission, opts ...grpc.CallOption) (*Submission, error) {
	out := new(Submission)
	err := c.cc.Invoke(ctx, "/api.SubmissionRepository/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *submissionRepositoryClient) Update(ctx context.Context, in *Submission, opts ...grpc.CallOption) (*Submission, error) {
	out := new(Submission)
	err := c.cc.Invoke(ctx, "/api.SubmissionRepository/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *submissionRepositoryClient) Delete(ctx context.Context, in *SubmissionRequestId, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.SubmissionRepository/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubmissionRepositoryServer is the server API for SubmissionRepository service.
// All implementations must embed UnimplementedSubmissionRepositoryServer
// for forward compatibility
type SubmissionRepositoryServer interface {
	All(context.Context, *Empty) (*SubmissionList, error)
	ById(context.Context, *SubmissionRequestId) (*Submission, error)
	Create(context.Context, *Submission) (*Submission, error)
	Update(context.Context, *Submission) (*Submission, error)
	Delete(context.Context, *SubmissionRequestId) (*Empty, error)
	mustEmbedUnimplementedSubmissionRepositoryServer()
}

// UnimplementedSubmissionRepositoryServer must be embedded to have forward compatible implementations.
type UnimplementedSubmissionRepositoryServer struct {
}

func (UnimplementedSubmissionRepositoryServer) All(context.Context, *Empty) (*SubmissionList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method All not implemented")
}
func (UnimplementedSubmissionRepositoryServer) ById(context.Context, *SubmissionRequestId) (*Submission, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ById not implemented")
}
func (UnimplementedSubmissionRepositoryServer) Create(context.Context, *Submission) (*Submission, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSubmissionRepositoryServer) Update(context.Context, *Submission) (*Submission, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedSubmissionRepositoryServer) Delete(context.Context, *SubmissionRequestId) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSubmissionRepositoryServer) mustEmbedUnimplementedSubmissionRepositoryServer() {}

// UnsafeSubmissionRepositoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubmissionRepositoryServer will
// result in compilation errors.
type UnsafeSubmissionRepositoryServer interface {
	mustEmbedUnimplementedSubmissionRepositoryServer()
}

func RegisterSubmissionRepositoryServer(s grpc.ServiceRegistrar, srv SubmissionRepositoryServer) {
	s.RegisterService(&SubmissionRepository_ServiceDesc, srv)
}

func _SubmissionRepository_All_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubmissionRepositoryServer).All(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SubmissionRepository/All",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubmissionRepositoryServer).All(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubmissionRepository_ById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmissionRequestId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubmissionRepositoryServer).ById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SubmissionRepository/ById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubmissionRepositoryServer).ById(ctx, req.(*SubmissionRequestId))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubmissionRepository_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Submission)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubmissionRepositoryServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SubmissionRepository/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubmissionRepositoryServer).Create(ctx, req.(*Submission))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubmissionRepository_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Submission)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubmissionRepositoryServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SubmissionRepository/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubmissionRepositoryServer).Update(ctx, req.(*Submission))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubmissionRepository_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmissionRequestId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubmissionRepositoryServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SubmissionRepository/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubmissionRepositoryServer).Delete(ctx, req.(*SubmissionRequestId))
	}
	return interceptor(ctx, in, info, handler)
}

// SubmissionRepository_ServiceDesc is the grpc.ServiceDesc for SubmissionRepository service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubmissionRepository_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.SubmissionRepository",
	HandlerType: (*SubmissionRepositoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "All",
			Handler:    _SubmissionRepository_All_Handler,
		},
		{
			MethodName: "ById",
			Handler:    _SubmissionRepository_ById_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _SubmissionRepository_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _SubmissionRepository_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SubmissionRepository_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/api/service.proto",
}
